# Generated by Django 4.2.21 on 2025-06-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_add_professor_and_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
