# Generated by Django 4.2.21 on 2025-05-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_crm', models.BooleanField(default=False)),
                ('can_access_tickets', models.BooleanField(default=False)),
                ('can_access_monitoring', models.BooleanField(default=False)),
                ('can_access_seletivo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
